# This template contains steps to run the language interop tests for a single configuration.

parameters:
  pool: ''
  image: ''
  platform: ''
  config: 'Debug'
  arch: 'x64'
  tls: ''
  logProfile: 'Basic.Light'
  testCerts: false
  extraArtifactDir: ''

jobs:
- job: lang_interop_${{ parameters.platform }}_${{ parameters.arch }}_${{ parameters.tls }}${{ parameters.extraArtifactDir }}
  displayName: ${{ parameters.platform }} ${{ parameters.arch }} ${{ parameters.tls }}${{ parameters.extraArtifactDir }}

  ${{ if ne(parameters.pool, '') }}:
    pool: ${{ parameters.pool }}
    workspace:
      clean: all
  ${{ if eq(parameters.pool, '') }}:
    pool:
      vmImage: ${{ parameters.image }}
  variables:
    runCodesignValidationInjection: false
  steps:
  - checkout: self

  - template: ./download-artifacts.yml
    parameters:
      platform: ${{ parameters.platform }}
      arch: ${{ parameters.arch }}
      tls: ${{ parameters.tls }}
      includeKernel: ${{ parameters.kernel }}
      extraArtifactDir: ${{ parameters.extraArtifactDir }}

  - task: PowerShell@2
    displayName: Prepare Test Machine
    inputs:
      pwsh: true
      filePath: scripts/prepare-machine.ps1
      ${{ if eq(parameters.testCerts, true) }}:
        arguments: -Configuration Test -TestCertificates
      ${{ if eq(parameters.testCerts, false) }}:
        arguments: -Configuration Test

  - task: PowerShell@2
    displayName: Run Lang Interop
    timeoutInMinutes: 5
    inputs:
      pwsh: true
      filePath: scripts/run-language-interop.ps1
      arguments: -AZP -NoProgress -IsolationMode Isolated -LogProfile ${{ parameters.logProfile }} -Config ${{ parameters.config }} -Arch ${{ parameters.arch }} -Tls ${{ parameters.tls }} ${{ parameters.extraArgs }}
